<?php

namespace App\Controller\Admin;

use App\Entity\Matchs;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class MatchsCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Matchs::class;
    }

    
    public function configureFields(string $pageName): iterable
    {
        return [
            IntegerField::new('id', 'ID')->onlyOnIndex(),
            AssociationField::new('user'),
            TextField::new('name'),
            TextField::new('startAt'),            
            ChoiceField::new('matchlevel')->setChoices(['TRAINING'=> '0',
                                                         'LEVEL I' => '1', 
                                                         'LEVEL II' => '2',
                                                         'LEVEL III' => '3',
                                                         'LEVEL VI' => '4',
                                                         'LEVEL V' => '5',
                                                       ]),
            TextField::new('MatchDirector'),
            TextField::new('RangeMaster'),
            TextField::new('StatsDirector'),

            ChoiceField::new('firearmtype')->setChoices([ 'Handgun' => '1', 
                                                          'Rifle' => '2',
                                                          'Shotgun' => '3',
                                                          'Action Air' => '5',
                                                          'Mini-Rifle' => '6',
                                                          'PCC' => '7',
                                                        ]),

             ChoiceField::new('clubName')->setChoices([ 'OTHER' => 'OTHER',
                                                        'ACADEMIE DE TIR 2000' => 'ACADEMIE DE TIR 2000',
                                                        'ACAPI CTS' => 'ACAPI CTS',
                                                        'ACOM' => 'ACOM',
                                                        'ANTC NOUMEA' => 'ANTC NOUMEA',
                                                        'AS FLERS MESSEI' => 'AS FLERS MESSEI',
                                                        'AS PEZENAS' => 'AS PEZENAS',
                                                        'AS SAINT MARTINOISE TIR' => 'AS SAINT MARTINOISE TIR',
                                                        'AS WITTENHEIM' => 'AS WITTENHEIM',
                                                        'ASBF-TSV' => 'ASBF-TSV',
                                                        'ASCDG' => 'ASCDG',
                                                        'ASOR ALTKIRCH' => 'ASOR ALTKIRCH',
                                                        'ASPL' => 'ASPL',
                                                        'AST ROISSY' => 'AST ROISSY',
                                                        'ASTAC' => 'ASTAC',
                                                        'ASTCP' => 'ASTCP',
                                                        'AT AQUITAIN' => 'AT AQUITAIN',
                                                        'AT BAQUI' => 'AT BAQUI',
                                                        'AT DE LA SORGUE' => 'AT DE LA SORGUE',
                                                        'AT MIMIZANAIS' => 'AT MIMIZANAIS',
                                                        'ATCBA' => 'ATCBA',
                                                        'ATCPA' => 'ATCPA',
                                                        'ATLAS' => 'ATLAS',
                                                        'ARQUEBUSE DE KOUROU' => 'ARQUEBUSE DE KOUROU',
                                                        'ARQUEBUSIERS DU PAYS D\'ANCENIS' => 'ARQUEBUSIERS DU PAYS D\\ANCENIS',
                                                        'ASSOCIATION TIR AUDENGEOISE' => 'ASSOCIATION TIR AUDENGEOISE',
                                                        'AS MAUZACAISE DE TIR CIBLE' => 'AS MAUZACAISE DE TIR CIBLE',
                                                        'AU PAS DE TIR DE BOERSCH' => 'AU PAS DE TIR DE BOERSCH',
                                                        'BRETAGNE TIR SPORTIF' => 'BRETAGNE TIR SPORTIF',
                                                        'CA' => 'CA',
                                                        'CAPR' => 'CAPR',
                                                        'CC ORANGE' => 'CC ORANGE',
                                                        'CENTRE DE TIR D\'ALSACE REGUISHEIM' => 'CENTRE DE TIR D\'ALSACE REGUISHEIM',
                                                        'CERCLE DE TIR VILLETOIS' => 'CERCLE DE TIR VILLETOIS',
                                                        'CIBLE MONT BLANC' => 'CIBLE MONT BLANC',
                                                        'CLT' => 'CLT',
                                                        'CLTS' => 'CLTS',
                                                        'CLUB CSA 1ER RCP PAMIERS' => 'CLUB CSA 1ER RCP PAMIERS',
                                                        'CLUB DE TIR VACANS DU TUCO' => 'CLUB DE TIR VACANS DU TUCO',
                                                        'CLUB DE TIR DE CAGNY' => 'CLUB DE TIR DE CAGNY',
                                                        'CLUB DE TIR DE LA VALOUZE' => 'CLUB DE TIR DE LA VALOUZE',
                                                        'CLUB DE TIR DU CASTELLAS' => 'CLUB DE TIR DU CASTELLAS',
                                                        'COMPLEXE DU TIR SPORTIF' => 'COMPLEXE DU TIR SPORTIF',
                                                        'CSA TIR 4EME RE' => 'CSA TIR 4EME RE',
                                                        'CSABA 123' => 'CSABA 123',
                                                        'CT GRENOBLOIS' => 'CT GRENOBLOIS',
                                                        'CT OCCITAN' => 'CT OCCITAN',
                                                        'CT ORCINOIS' => 'CT ORCINOIS',
                                                        'CT TARASCONNAIS' => 'CT TARASCONNAIS',
                                                        'CT VOREPPIN' => 'CT VOREPPIN',
                                                        'CTCM' => 'CTCM',
                                                        'CTCMR' => 'CTCMR',
                                                        'CTFC' => 'CTFC',
                                                        'CTMN' => 'CTMN',
                                                        'CTMU' => 'CTMU',
                                                        'CTP STEPHANOIS' => 'CTP STEPHANOIS',
                                                        'CTP VAROIS' => 'CTP VAROIS',
                                                        'CTS VERNON' => 'CTS VERNON',
                                                        'CTPN' => 'CTPN',
                                                        'CTS MACOURIA' => 'CTS MACOURIA',
                                                        'CTST' => 'CTST',
                                                        'CTSVE' => 'CTSVE',
                                                        'CTTB' => 'CTTB',
                                                        'CLUB DE TIR D\'AUVOURS' => 'CLUB DE TIR D\'AUVOURS',
                                                        'DOUBLE ALPHA DU RACAN' => 'DOUBLE ALPHA DU RACAN',
                                                        'IMPACT VANNES' => 'IMPACT VANNES',
                                                        'ISARDS DE BIGORRE' => 'ISARDS DE BIGORRE',
                                                        'JEFF COOPER 45' => 'JEFF COOPER 45',
                                                        'L\'ARQUEBUSE' => 'L\'ARQUEBUSE',
                                                        'LES PIONNIERS BRESSANS' => 'LES PIONNIERS BRESSANS',
                                                        'LES TIREURS DE LA VOIE ROMAINE' => 'LES TIREURS DE LA VOIE ROMAINE',
                                                        'LES TIREURS DE L\'UZEGE' => 'LES TIREURS DE L\'UZEGE',
                                                        'LES ARQUEBUSIERS DE MARENNES' => 'LES ARQUEBUSIERS DE MARENNES',
                                                        'LES CHEVALIERS DE l\'ARQUEBUSE DE CHAGNY' => 'LES CHEVALIERS DE l\'ARQUEBUSE DE CHAGNY',
                                                        'LES TIREURS DU ROC NOIR' => 'LES TIREURS DU ROC NOIR',
                                                        'MARONI TIR' => 'MARONI TIR',
                                                        'PA' => 'PA',
                                                        'PATRIE TIR LOON PLAGE' => 'PATRIE TIR LOON PLAGE',
                                                        'PROVENCE TIR' => 'PROVENCE TIR',
                                                        'RCM' => 'RCM',
                                                        'RCW' => 'RCW',
                                                        'Selongey TS' => 'Selongey TS',
                                                        'STAC' => 'STAC',
                                                        'STAP' => 'STAP',
                                                        'ST AUBIGNE RACAN' => 'ST AUBIGNE RACAN',
                                                        'ST Besancon' => 'ST Besancon',
                                                        'ST DU JURA' => 'ST DU JURA',
                                                        'ST PAMIERS' => 'ST PAMIERS',
                                                        'ST QUIBERON' => 'ST QUIBERON',
                                                        'ST REGION ALBERTVILLE' => 'ST REGION ALBERTVILLE',
                                                        'ST REIMS' => 'ST REIMS',
                                                        'ST THELOD' => 'ST THELOD',
                                                        'STADE NIORTAIS TIR' => 'STADE NIORTAIS TIR',
                                                        'STAND 29' => 'STAND 29',
                                                        'STC VERTUS' => 'STC VERTUS',
                                                        'ST EPINAL' => 'ST EPINAL',
                                                        'STE DE TIR AMITIE' => 'STE DE TIR AMITIE',
                                                        'STE DE TIR DE FAREMOUTIERS' => 'STE DE TIR DE FAREMOUTIERS',
                                                        'STE DE TIR DE LANGLADE' => 'STE DE TIR DE LANGLADE',
                                                        'STE DE TIR SAINT SEBASTIEN' => 'STE DE TIR SAINT SEBASTIEN',
                                                        'STE TREMBLADAISE TIR' => 'STE TREMBLADAISE TIR',
                                                        'STE VAUVERDOISE' => 'STE VAUVERDOISE',
                                                        'STPO Lavelanet' => 'STPO Lavelanet',
                                                        'TC ABYMES' => 'TC ABYMES',
                                                        'TC LAURENTIN' => 'TC LAURENTIN',
                                                        'TCFO' => 'TCFO',
                                                        'TDL' => 'TDL',
                                                        'TIR CLUB CIOTADEN' => 'TIR CLUB CIOTADEN',
                                                        'TIR CLUB SATURINOIS' => 'TIR CLUB SATURINOIS',
                                                        'TIR OLYMPIQUE LEZOVIEN' => 'TIR OLYMPIQUE LEZOVIEN',
                                                        'TIREURS VOIE ROMAINE' => 'TIREURS VOIE ROMAINE',
                                                        'TNV' => 'TNV',
                                                        'TO AQUITAIN' => 'TO AQUITAIN',
                                                        'TOL' => 'TOL',
                                                        'TOV' => 'TOV',
                                                        'TS LUNEVILLE' => 'TS LUNEVILLE',
                                                        'TS MANDALLAZ' => 'TS MANDALLAZ',
                                                        'TS MAURES' => 'TS MAURES',
                                                        'TSCA' => 'TSCA',
                                                        'TSCB' => 'TSCB',
                                                        'TSCP' => 'TSCP',
                                                        'TSL PERRIGNY LES DIJONS' => 'TSL PERRIGNY LES DIJONS',
                                                        'US CAGNES TIR CLUB' => 'US CAGNES TIR CLUB',
                                                        'US LE ROCHER TIR' => 'US LE ROCHER TIR',
                                                        'VAR PISTOL SHOOTING' => 'VAR PISTOL SHOOTING',
                                                        'OEILLETON CERIZEEN' => 'OEILLETON CERIZEEN'  ,
                                                        ]),

            ChoiceField::new('CountryId')->setChoices(['OTHER' => 'OTHER',
                                                        'AND Andorra' => 'AND Andorra',
                                                        'ARG Argentina' => 'ARG Argentina',
                                                        'ARU Aruba' => 'ARU Aruba',
                                                        'AUS Australia' => 'AUS Australia',
                                                        'AUT Austria' => 'AUT Austria',
                                                        'BAR Barbados' => 'BAR Barbados',
                                                        'BLR Belarus' => 'BLR Belarus',
                                                        'BEL Belgium' => 'BEL Belgium',
                                                        'BOL Bolivia' => 'BOL Bolivia',
                                                        'BIH Bosnia Herzegovina' => 'BIH Bosnia Herzegovina',
                                                        'BRA Brazil' => 'BRA Brazil',
                                                        'BUL Bulgaria' => 'BUL Bulgaria',
                                                        'CAM Cambodia' => 'CAM Cambodia',
                                                        'CAN Canada' => 'CAN Canada',
                                                        'CAY Cayman Islands' => 'CAY Cayman Islands',
                                                        'CNI Channel Islands' => 'CNI Channel Islands',
                                                        'CHI Chile' => 'CHI Chile',
                                                        'CHN China' => 'CHN China',
                                                        'COL Colombia' => 'COL Colombia',
                                                        'CRC Costa Rica' => 'CRC Costa Rica',
                                                        'CRO Croatia' => 'CRO Croatia',
                                                        'CUW Curacao' => 'CUW Curacao',
                                                        'CYP Cyprus' => 'CYP Cyprus',
                                                        'CZE Czech Republic' => 'CZE Czech Republic',
                                                        'DEN Denmark' => 'DEN Denmark',
                                                        'ECU Ecuador' => 'ECU Ecuador',
                                                        'ESA El Salvador' => 'ESA El Salvador',
                                                        'EST Estonia' => 'EST Estonia',
                                                        'FIJ Fiji' => 'FIJ Fiji',
                                                        'FIN Finland' => 'FIN Finland',
                                                        'FRA France' => 'FRA France',
                                                        'GER Germany' => 'GER Germany',
                                                        'GIB Gibraltar' => 'GIB Gibraltar',
                                                        'GBR Great Britain' => 'GBR Great Britain',
                                                        'GRE Greece' => 'GRE Greece',
                                                        'GRN Grenada' => 'GRN Grenada',
                                                        'GUM Guam' => 'GUM Guam',
                                                        'GUA Guatemala' => 'GUA Guatemala',
                                                        'GUY Guyana' => 'GUY Guyana',
                                                        'HON Honduras' => 'HON Honduras',
                                                        'HKG Hong Kong' => 'HKG Hong Kong',
                                                        'HUN Hungary' => 'HUN Hungary',
                                                        'INA Indonesia' => 'INA Indonesia',
                                                        'IRL Ireland, Republic Of' => 'IRL Ireland, Republic Of',
                                                        'IOM Isle Of Man' => 'IOM Isle Of Man',
                                                        'ISR Israel' => 'ISR Israel',
                                                        'ITA Italy' => 'ITA Italy',
                                                        'JAM Jamaica' => 'JAM Jamaica',
                                                        'JPN Japan' => 'JPN Japan',
                                                        'KAZ Kazakhstan' => 'KAZ Kazakhstan',
                                                        'KEN Kenya' => 'KEN Kenya',
                                                        'KOR Korea, Republic Of' => 'KOR Korea, Republic Of',
                                                        'KUW Kuwait' => 'KUW Kuwait',
                                                        'LAO Laos' => 'LAO Laos',
                                                        'LAT Latvia' => 'LAT Latvia',
                                                        'LBN Lebanon' => 'LBN Lebanon',
                                                        'LTU Lithuania' => 'LTU Lithuania',
                                                        'MAC Macau' => 'MAC Macau',
                                                        'MAS Malaysia' => 'MAS Malaysia',
                                                        'MLT Malta' => 'MLT Malta',
                                                        'MEX Mexico' => 'MEX Mexico',
                                                        'MDA Moldova' => 'MDA Moldova',
                                                        'MON Monaco' => 'MON Monaco',
                                                        'MGL Mongolia' => 'MGL Mongolia',
                                                        'MTO Montenegro' => 'MTO Montenegro',
                                                        'NAM Namibia' => 'NAM Namibia',
                                                        'NED Netherlands' => 'NED Netherlands',
                                                        'NZL New Zealand' => 'NZL New Zealand',
                                                        'NCA Nicaragua' => 'NCA Nicaragua',
                                                        'NIR Northern Ireland' => 'NIR Northern Ireland',
                                                        'NOR Norway' => 'NOR Norway',
                                                        'PAK Pakistan' => 'PAK Pakistan',
                                                        'PAN Panama' => 'PAN Panama',
                                                        'PNG Papua New Guinea' => 'PNG Papua New Guinea',
                                                        'PAR Paraguay' => 'PAR Paraguay',
                                                        'PER Peru' => 'PER Peru',
                                                        'PHI Philippines' => 'PHI Philippines',
                                                        'POL Poland' => 'POL Poland',
                                                        'POR Portugal' => 'POR Portugal',
                                                        'PUR Puerto Rico' => 'PUR Puerto Rico',
                                                        'QAT Qatar' => 'QAT Qatar',
                                                        'ROU Romania' => 'ROU Romania',
                                                        'RUS Russia' => 'RUS Russia',
                                                        'LCA Saint Lucia' => 'LCA Saint Lucia',
                                                        'SER Serbia' => 'SER Serbia',
                                                        'SIN Singapore' => 'SIN Singapore',
                                                        'SVK Slovak Republic' => 'SVK Slovak Republic',
                                                        'SLO Slovenia' => 'SLO Slovenia',
                                                        'RSA South Africa' => 'RSA South Africa',
                                                        'ESP Spain' => 'ESP Spain',
                                                        'SRI Sri Lanka' => 'SRI Sri Lanka',
                                                        'SUR Suriname' => 'SUR Suriname',
                                                        'SWZ Swaziland' => 'SWZ Swaziland',
                                                        'SWE Sweden' => 'SWE Sweden',
                                                        'SUI Switzerland' => 'SUI Switzerland',
                                                        'TPE Taiwan' => 'TPE Taiwan',
                                                        'THA Thailand' => 'THA Thailand',
                                                        'TRI Trinidad And Tobago' => 'TRI Trinidad And Tobago',
                                                        'TUR Turkey' => 'TUR Turkey',
                                                        'UKR Ukraine' => 'UKR Ukraine',
                                                        'UAE United Arab Emirates' => 'UAE United Arab Emirates',
                                                        'USA United States' => 'USA United States',
                                                        'URU Uruguay' => 'URU Uruguay',
                                                        'VEN Venezuela' => 'VEN Venezuela',
                                                        'ZIM Zimbabwe' => 'ZIM Zimbabwe',
                                                       ]),

            ChoiceField::new('SquadCount')->setChoices(['1' => '1', 
                                                        '2' => '2',
                                                        '3' => '3',
                                                        '4' => '4',
                                                        '5' => '5',
                                                        '6' => '6',
                                                        '7' => '7',
                                                        '8' => '8',
                                                        '9' => '9',
                                                        '10' => '10',
                                                        ]),

            ChoiceField::new('matchid')->setChoices(['1' => '1', 
                                                        '2' => '2',
                                                        '3' => '3',
                                                        '4' => '4',
                                                        '5' => '5',
                                                        '6' => '6',
                                                        '7' => '7',
                                                        '8' => '8',
                                                        '9' => '9',
                                                        '10' => '10',
                                                        ]),            
            DateTimeField::new('created_at'),
            DateTimeField::new('updated_at'),
            CollectionField::new('stages'),


        ];
    }
    
}